---
- hosts: localhost

  tasks:
    - include_vars: vars.yaml
    - name: Install tools and libs
      community.general.homebrew:
        name: "{{brew_revision}}"
        state: present
        update_homebrew: yes
    - name: Execute change-brew-repo.sh
      script: change-brew-repo.sh